### ISSUE TITLE
Use tag for SPA type tags

### ISSUE THREAD

**Issue by jwoertink** [yjukaku/html2lucky#11]
Hello, and thanks for your work on this project.

I have a found a bug when using this site. Here are the details:

### The minimal amount of HTML input that triggers the bug

```html
<h3 class="sort-label">
      <font-awesome-icon icon="sort"></font-awesome-icon>
      Sort Options
</h3>
```

### What I expected to be output when inputting the minimal HTML above

```crystal
h3 class: "sort-lable" do
  tag("font-awesome-icon", icon: "sort")
  text "Sort Options"
end
```

### What is actually output by the site

```crystal
h3 class: "sort-label" do
    font-awesome-icon "" icon: "sort"
    text " Sort Options "
end
```

I will wait patiently as you work on this free project in your precious spare time. Thank you again!

**Comment by paulcsmith** [comment]
Thanks for opening this @jwoertink. Definitely needs to be improved. I'd also like to make the design match the new website and host it on website-v2 directly!

**Comment by jwoertink** [comment]
For sure! Now that the site is built in lucky, we can definitely just integrate this engine.

**Comment by jwoertink** [comment]
ok, weird... I just tried to fix this, and found there's a spec for it https://github.com/luckyframework/html2lucky/blob/master/spec/converter_spec.cr#L193-L219. When I run the spec locally, it passes. I wrote an additional spec for the code above, and it prints what it actually should.

My guess is the latest master version isn't deployed? Now, the app was upgraded recently to support crystal 0.29, but the Lucky version wasn't updated to match. I had to monkey patch Lucky just to run specs.

**Comment by paulcsmith** [comment]
I think you’re right! I’ll try to deploy in a few mins :)

**Comment by paulcsmith** [comment]
Actually what site are you visiting? There is an old one and there is this one with tons of improvements. The link should be in the repo home page

**Comment by jwoertink** [comment]
ugh. Yup. I did this last time too. My browser has the other one cached, so that's the first one I always go to.
